[common]
;API mode, set to true to prevent loading local subscriptions or serving local files directly
api_mode=true

;Access token used for performing critical action through Web interface
api_access_token=password

;Default URLs, used when no URL is provided in request, use "|" to separate multiple subscription links, supports local files/URL
default_url=

;Insert subscription links to requests. Can be used to add node(s) to all exported subscriptions.
enable_insert=true

;URLs to insert to subscription links, use "|" to separate multiple subscription links, supports local files/URL
insert_url=

;Prepend inserted URLs to subscription links. Nodes in insert_url will be added to groups first with non-group-specific match pattern.
prepend_insert_url=true

;Exclude nodes which remarks match the following patterns. Supports regular expression.
exclude_remarks=(剩余流量|到期|时间|官网|产品|平台)
;exclude_remarks=(.*流量.*等级.*剩.*天)
;exclude_remarks=(.*流量.*剩.*天)
;exclude_remarks=(■等级警报■)
;exclude_remarks=(\[限速\])
;exclude_remarks=(\[游戏\])
;exclude_remarks=(\[游戏专用\])
;exclude_remarks=流量耗尽
;exclude_remarks=(近期下线)
;exclude_remarks=(游戏专线)
;exclude_remarks=(维护)
;exclude_remarks=(\[孬\])
;exclude_remarks=(other rule)

;Only include nodes which remarks match the following patterns. Supports regular expression.
;include_remarks=V3.*港

;Enable script support for filtering nodes
enable_filter=false
;Script used for filtering nodes. Supports inline script and script path. A "filter" function with 1 argument which is a node should be defined in the script.
;Example: Inline script: Set value to content of script. Replace all line break with "\n".
;         Script path: Set value to "path:/path/to/script.js".
;filter_script=function filter(node) {\n    const info = JSON.parse(node.ProxyInfo);\n    if(info.EncryptMethod.includes('chacha20'))\n        return true;\n    return false;\n}

;Setting an external config file as default when none is specified, supports local files/URL
default_external_config=https://raw.githubusercontent.com/LM-Firefly/Rules/master/Subconverter-base/AIO.ini

;The file scope limit of the 'rule_base' options in external configs.
base_path=base

;Clash config base used by the generator, supports local files/URL
clash_rule_base=https://raw.githubusercontent.com/LM-Firefly/Rules/master/Subconverter-base/all-base.tpl
;https://raw.githubusercontent.com/LM-Firefly/Rules/master/Subconverter-base/Clash-General.yaml

;Surge config base used by the generator, supports local files/URL
surge_rule_base=base/all-base.tpl

;Surfboard config base used by the generator, supports local files/URL
surfboard_rule_base=https://raw.githubusercontent.com/LM-Firefly/Rules/master/Subconverter-base/Surfboard-General.conf

;Mellow config base used by the generator, supports local files/URL
mellow_rule_base=base/all-base.tpl

;Quantumult config base used by the generator, supports local files/URL
quan_rule_base=base/all-base.tpl

;Quantumult X config base used by the generator, supports local files/URL
quanx_rule_base=base/all-base.tpl

;Loon config base used by the generator, supports local files/URL
loon_rule_base=base/all-base.tpl

;Shadowsocks Android config base used by the generator, supports local files/URL
sssub_rule_base=base/all-base.tpl

;Proxy used to download configs, rulesets or subscriptions, set to NONE or empty to disable it, set to SYSTEM to use system proxy.
;Accept cURL-supported proxies (http:// https:// socks4a:// socks5://)
;Additional support for CORS proxy ( https://github.com/Rob--W/cors-anywhere https://github.com/Zibri/cloudflare-cors-anywhere etc.), prefix the address with "cors:" to recognize the address as CORS proxy.
;Example:  http://127.0.0.1:80  socks5://example.com:1080  cors:https://cors-anywhere.herokuapp.com/
proxy_config=SYSTEM
proxy_ruleset=SYSTEM
proxy_subscription=SYSTEM

;Append a proxy type string ([SS] [SSR] [VMess]) to node remark.
append_proxy_type=false

[userinfo]
;Rules to extract stream data from node
;Format: full_match_regex|new_format_regex
;where new_format_regex should be like "total=$1&left=$2&used=$3"
;stream_rule=^剩余流量：(.*?)\|总流量：(.*)$|total=$2&left=$1
;stream_rule=^剩余流量：(.*?) (.*)$|total=$1&left=$2
;stream_rule=^Bandwidth: (.*?)/(.*)$|used=$1&total=$2
;stream_rule=^\[.*?\]剩余(.*?)@(?:.*)$|total=$1
;stream_rule=^.*?流量:(.*?) 剩:(?:.*)$|total=$1

;Rules to extract expire time data from node
;Format: full_match_regex|new_format_regex
;where new_format_regex should follow this example: yyyy:mm:dd:hh:mm:ss
;time_rule=^过期时间：(\d+)-(\d+)-(\d+) (\d+):(\d+):(\d+)$|$1:$2:$3:$4:$5:$6
;time_rule=^到期时间(:|：)(\d+)-(\d+)-(\d+)$|$1:$2:$3:0:0:0
;time_rule=^Smart Access expire: (\d+)/(\d+)/(\d+)$|$1:$2:$3:0:0:0
;time_rule=^.*?流量:(?:.*?) 剩:(.*)$|left=$1d

[node_pref]
udp_flag=true
tcp_fast_open_flag=true
skip_cert_verify_flag=false
tls13_flag=true

sort_flag=true
;Script used for sorting nodes. A "compare" function with 2 arguments which are the 2 nodes to be compared should be defined in the script. Supports inline script and script path.
;Examples can be seen at the filter_script option in [common] section.
;sort_script=function compare(node_a, node_b) {\n    const info_a = JSON.parse(node_a.ProxyInfo);\n    const info_b = JSON.parse(node_b.ProxyInfo);\n    return info_a.Remark > info_b.Remark;\n}

filter_deprecated_nodes=false
append_sub_userinfo=false
clash_use_new_field_name=true

;Generate style of the proxies section of Clash subscriptions.
;Supported styles: block, flow, compact
;Block: - name: name1    Flow: - {name: name1, key: value}    Compact: [{name: name1, key: value},{name: name2, key: value}]
;         key: value           - {name: name2, key: value}
;       - name: name2
;         key: value
clash_proxies_style=flow

;Rename remarks with the following patterns. Supports regular expression.
;Format: Search_Pattern@Replace_Pattern
;rename=商宽@
;rename=移动@CM
;rename=电信@CT
;rename=联通@CU
;rename=上海@沪
;rename=中国@中
;rename=云南@云
;rename=佛山@禅
;rename=俄罗斯@俄
;rename=加拿大@加
;rename=北京@京
;rename=南京@宁
;rename=南阳@宛
;rename=印度@印
;rename=台湾@台
;rename=四川@川
;rename=土耳其@土
;rename=天津@津
;rename=宁波@甬
;rename=安徽@皖
;rename=广东@粤
;rename=广州@穗
;rename=徐州@徐
;rename=德国@德
;rename=意大利@意
;rename=成都@蓉
;rename=新加坡@新
;rename=日本@日
;rename=杭州@杭
;rename=武汉@汉
;rename=汕头@汕
;rename=江苏@苏
;rename=沈阳@沈
;rename=法国@法
;rename=泰国@泰
;rename=浙江@浙
;rename=海南@琼
;rename=深圳@深
;rename=湖北@鄂
;rename=湖南@湘
;rename=澳门@澳
;rename=珠海@珠
;rename=瑞士@瑞
;rename=福建@闽
;rename=美国@美
;rename=芬兰@芬
;rename=英国@英
;rename=菲律宾@菲
;rename=许昌@许
;rename=贵州@贵
;rename=贵阳@筑
;rename=越南@越
;rename=镇江@镇
;rename=青岛@青
;rename=青海@青
;rename=韩国@韩
;rename=香港@港
;rename=深港专线@深港
;rename=(-)@▷
;rename=隧道测试@
;rename=隧道@
;rename=隧道测试[0-9]组@
;rename=[0-9]组@
;rename=⓪@
;rename=^(.*)V2\.@
;rename=^(.*)TJ\.@
;rename=❖CN[0-9]❖@
;rename=^(.*)(HK(?!(B|T|G)))([\u4e00-\u9fa5])@港-$3
;rename=^(.*)(HK(?!B|G|T))([\u4e00-\u9fa5].*)@港-$3
;rename=^(HKBN)(.*)@港HKBN-$2
;rename=^(HKG)(.*)@港HKG-$2
;rename=^(HKT)(.*)@港HKT-$2
;rename=^(HGC)(.*)@港HGC-$2
;rename=^(WTT)(.*)@港WTT-$2
;rename=^(US)(.*)@美-$2
;rename=^(JP)(.*)@日-$2
;rename=^(TW)(.*)@台-$2
;rename=^(SG)(.*)@新-$2
;rename=^(RU)(.*)@俄-$2
;rename=^(TR)(.*)@土-$2
;rename=^(UK)(.*)@英-$2
;rename=^(KR)(.*)@韩-$2
;rename=^(FR)(.*)@法-$2
;rename=^(CA)(.*)@加-$2
;rename=^(CN)(.*)@中-$2
;rename=^(RO)(.*)@罗马尼亚-$2
;rename=(--)@
;rename=\[CM\]@
;rename=\[仅CM可用\]@
;rename=\[BT/PT专用\]@
;rename=\[荐\]@
;rename=\[Beta\]@
;rename=\[临时\]@
;rename=\[移动\]@
;rename=\[联通\]@
;rename=\[仅移动可用\]@
;rename=\[綜合\]@
;rename=\[综合\]@
;rename=\[回国\]@
;rename=\[中转\]@
;rename=\[备用\]@
;rename=\[阿里云\]@
;rename=\[.*NF.*\]@
;rename=\[.*Hulu.*\]@
;rename=\[注册Netflix\]@
;rename=\[.*BBC.*\]@
;rename=\[v6\]@
;rename=\[0\.2\]@[倍率:0.2]
;rename=\[0\.5\]@[倍率:0.5]
;rename=\[0\.7\]@[倍率:0.7]
;rename=\[0\.8\]@[倍率:0.8]
;rename=\[0\.9\]@[倍率:0.9]
;rename=\[1\]@[倍率:1]
;rename=\[1\.2\]@[倍率:1.2]
;rename=\[1\.5\]@[倍率:1.5]
;rename=\[2\]@[倍率:2]
;rename=\[5\]@[倍率:5]
;rename=\[8\]@[倍率:8]
;rename=\[10\]@[倍率:10]
;rename=(?!<=[\]|\)])$@[倍率:1]
;rename= @
;rename=[ ]@
;rename=( )@

;rename_node=!!script:function rename(node) {\n  const info = JSON.parse(node.ProxyInfo);\n  const geoinfo = JSON.parse(geoip(info.Hostname));\n  if(geoinfo.country_code == "CN")\n    return "CN " + node.Remark;\n}
;rename_node=!!script:path:/path/to/script.js

rename_node=!!import:snippets/rename_node.txt

[managed_config]
;Append a '#!MANAGED-CONFIG' info to Surge configurations
write_managed_config=true

;Address prefix for MANAGED-CONFIG info, without the trailing "/".
;This address will also be used for generating /getruleset, /qx-rewrite, /qx-script addresses.
managed_config_prefix=http://127.0.0.1:25500

;Managed config update interval in seconds, determine how long the config will be updated.
config_update_interval=86400

;If config_update_strict is set to true, Surge will require a force update after the interval.
config_update_strict=false

;Device ID to be written to rewrite scripts for some version of Quantumult X
quanx_device_id=

[surge_external_proxy]
;surge_ssr_path=/usr/bin/ssr-local
resolve_hostname=true

[emojis]
add_emoji=true
remove_old_emoji=true

;Rule to add emojis. Supports regular expression.
;Format: Remark_Search_Pattern,emoji

;rule=(流量|时间|应急|过期|Bandwidth|expire),🏳️‍🌈
;rule=AC,🇦🇨

;rule=(?i:流量|时间|应急|过期|Bandwidth|expire),🏳️‍🌈
;rule=AC,🇦🇨
;rule=(AR|阿根廷),🇦🇷
;rule=(奥地利|维也纳),🇦🇹
;rule=(AU|Australia|Sydney|澳大利亚|悉尼),🇦🇺
;rule=BE,🇧🇪
;rule=(BR|Brazil|巴西|圣保罗),🇧🇷
;rule=(Canada|加(?!州).*(?!▷)|蒙特利尔|温哥华|楓葉|枫叶|CA),🇨🇦
;rule=(瑞士|苏黎世),🇨🇭
;rule=(DE|Germany|法兰克福|德.*(?!▷)),🇩🇪
;rule=丹麦,🇩🇰
;rule=ES,🇪🇸
;rule=EU,🇪🇺
;rule=(Finland|芬兰|赫尔辛基),🇫🇮
;rule=(FR|France|法国|巴黎),🇫🇷
;rule=(UK|England|UnitedKingdom|英.*(?!▷)|伦敦),🇬🇧
;rule=(HK|HongKong|HKT|HKBN|HGC|WTT|CMI|港(?!▷|回)),🇭🇰
;rule=(Indonesia|印尼|印度尼西亚|雅加达),🇮🇩
;rule=(Ireland|爱尔兰|都柏林),🇮🇪
;rule=(India|印度|孟买),🇮🇳
;rule=(Italy|意大利|米兰),🇮🇹
;rule=(JP|Japan|日.*(?!▷)|东京|大阪|埼玉|沪日|穗日|川日|中日|泉日|杭日),🇯🇵
;rule=(KP|朝鲜),🇰🇵
;rule=(KR|Korea|KOR|首尔|韩|韓),🇰🇷
;rule=(MO|Macao|澳.*(?!▷)|CTM),🇲🇴
;rule=(MY|Malaysia|马来西亚),🇲🇾
;rule=(NL|Netherlands|荷兰|阿姆斯特丹),🇳🇱
;rule=(PH|Philippines|菲律宾),🇵🇭
;rule=(RO|罗马尼亚),🇷🇴
;rule=(RU|Russia|俄.*(?!▷)|伯力|莫斯科|圣彼得堡|西伯利亚|新西伯利亚|哈巴罗夫斯克|俄罗斯|京俄|杭俄),🇷🇺
;rule=(沙特|迪拜),🇸🇦
;rule=(SE|Sweden),🇸🇪
;rule=(SG|Singapore|新.*(?!▷)|狮城|沪新|京新|泉新|穗新|深新|杭新),🇸🇬
;rule=(TH|Thailand|泰国|曼谷),🇹🇭
;rule=(TR|Turkey|土.*(?!▷)|伊斯坦布尔),🇹🇷
;rule=(US|America|United.*?States|美.*(?!▷)|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|沪美|京美),🇺🇲
;rule=(VN|越南),🇻🇳
;rule=(ZA|南非),🇿🇦
;rule=(台.*(?!▷)|台北|台中|新北|彰化|TW|Taiwan|CHT|HiNet),🇹🇼
;rule=(CN|China|回国|中.*(?!▷)|苏.*(?!▷)|京.*(?!▷)|沪.*(?!▷)|穗.*(?!▷)|深(?!▷|港)|杭.*(?!▷)|徐.*(?!▷)|青.*(?!▷)|甬.*(?!▷)|镇.*(?!▷)|禅.*(?!▷)|蓉.*(?!▷)|back),🇨🇳
;rule=(NetEaseMusic|网易云音乐|网易云解锁),🎵

;rule=!!script:function getEmoji(node) {\n  const info = JSON.parse(node.ProxyInfo);\n  const geoinfo = JSON.parse(geoip(info.Hostname));\n  if(geoinfo.country_code == "CN")\n    return "🏳️‍🌈";\n}
;rule=!!script:path:/path/to/script/.js

rule=!!import:snippets/emoji.txt

[rulesets]
;Enable generating rules with rulesets
enabled=true

;Overwrite the existing rules in rule_base
overwrite_original_rules=true

;Perform a ruleset update on request
update_ruleset_on_request=true

;Ruleset addresses, supports local files/URL
;Format: Group name,[type:]URL[,interval]
;        Group name,[]Rule
;where "type" supports the following value: surge, quanx, clash-domain, clash-ipcidr, clash-classic
;type defaults to surge if omitted

ruleset=!!import:snippets/rulesets.txt

[proxy_groups]
;Generate Clash Proxy Group with the following patterns. Node filtering rule supports regular expression.
;Format: Group_Name`select`Rule_1`Rule_2`...
;        Group_Name`url-test|fallback|load-balance`Rule_1`Rule_2`...`test_url`interval[,timeout][,tolerance]
;Rule with "[]" prefix will be added directly.

;custom_proxy_group=Proxy`select`.*`[]AUTO`[]DIRECT`.*
;custom_proxy_group=UrlTest`url-test`.*`http://www.gstatic.com/generate_204`300,5,100
;custom_proxy_group=FallBack`fallback`.*`http://www.gstatic.com/generate_204`300,5
;custom_proxy_group=LoadBalance`load-balance`.*`http://www.gstatic.com/generate_204`300,,100
;custom_proxy_group=SSID`ssid`default_group`celluar=group0,ssid1=group1,ssid2=group2

;custom_proxy_group=g1`select`!!GROUPID=0
;custom_proxy_group=g2`select`!!GROUPID=1
;custom_proxy_group=v2ray`select`!!GROUP=V2RayProvider

;custom_proxy_group=g1hk`select`!!GROUPID=0!!(HGC|HKBN|PCCW|HKT|hk|港)
;custom_proxy_group=sstw`select`!!GROUP=V2RayProvider!!(深台|彰化|新北|台|tw)
;custom_proxy_group=provider`select`!!PROVIDER=prov1,prov2,prov3`fallback_nodes

;Also supports using script for filtering nodes. A "filter" function with one argument which is an array of all available nodes should be defined in the script.
;custom_proxy_group=script`select`script:/path/to/script.js

;for forcerule.yml
;custom_proxy_group=!!import:snippets/groups_forcerule.txt

;for Surge rulesets
custom_proxy_group=!!import:snippets/groups.txt

[template]
;The file scope limit of 'include' statement inside the templates.
template_path=templates

;The following settings will be added to the "global" scope of the template variables
;Value of 'clash.http_port' can be accessed with 'global.clash.http_port' in the template.
clash.mixed_port=8888
clash.redir_port=8890
clash.allow_lan=true
clash.log_level=info

[aliases]
;Aliases for accessing interfaces. Can be used to shorten the URI.
;All arguments passed when accessing the alias name will be appended to the arguments of the alias target.
;Format: uri=target
/v=/version
/clash=/sub?target=clash
/clashr=/sub?target=clashr
/surge=/sub?target=surge
/quan=/sub?target=quan
/quanx=/sub?target=quanx
/mellow=/sub?target=mellow
/surfboard=/sub?target=surfboard
/loon=/sub?target=loon
/ss=/sub?target=ss
/ssd=/sub?target=ssd
/sssub=/sub?target=sssub
/ssr=/sub?target=ssr
/v2ray=/sub?target=v2ray
/trojan=/sub?target=trojan

;Profile example
/AIO=/getprofile?name=profiles/AIO.ini

[server]
;Address to bind on for Web Server
listen=0.0.0.0

;Port to bind on for Web Server
port=25500

;Root folder for web server, keep empty to disable
serve_file_root=

[advanced]
log_level=debug
print_debug_info=false
max_pending_connections=10240
max_concurrent_threads=4
max_allowed_rulesets=144
max_allowed_rules=665533
max_allowed_download_size=0
enable_cache=false
cache_subscription=60
cache_config=300
cache_ruleset=10800
async_fetch_ruleset=true
skip_failed_links=false
